using EmployeeManagement_Blazor.Client;
using EmployeeManagement_Blazor.Client.Services;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Syncfusion.Blazor;



Syncfusion.Licensing.SyncfusionLicenseProvider.RegisterLicense("NDQyMTI4QDMxMzkyZTMxMmUzMGRuZm5HZW5nNkJqbUJINXFTU3RnNjByV3FNdXpLTmduNVd5VEZSTGhYdk09;NDQyMTISQDMxMzkyZTMxMmUzMGZ3SWxkTWNSWVJuYTJIMkQrdk1Ud3phV29LcXZYMINrcEpqNEhBd09xMWM9;NDQyMTMwQDMxMzkyZTMxMmUzMGlnKzBMSWpUbkp5bUSDUnBlVzZSOFhKR3FPOVBnd3pNcU90NUhwWDA1T2s9;NDQyMTMxQDMxMzkyZTMxMmUzMEpxWHpTODZjUEtGdDhCcnE1TCtBcDJaUmISMUxIMFZsSEJxb1Z6cFpxaTA9;NDQyMTMyQDMxMzkyZTMxMmUzMEJSMGdoMIFpakQ5WjhGYnRGQ2Q5bUMvNWJzWHFuNisweHFseWhLTHQ3aU09;NDQyMTMzQDMxMzkyZTMxMmUzMEFrSyszaVivQniza0dSZjZRTythQONPUk9SdC9sTkg5RjBOUEg4Qlc5TWM9;NDQyMTM0QDMxMzkyZTMxMmUzMFRKMW8vUXpTU2JabHFNSE9YeGJNQ2JTM3dhdm45eTJUeGx5aGJUMOxydTA9;NDQyMTM1QDMxMzkyZTMxMmUzMGRST3N3d1 dMbDhCT31jMXNGVHU1Tnlxbnc5Q21wRVdrbUFnNmNWd2dUVJA9;NDQyMTM2QDMxMzkyZTMxMmUzMEx0b1BFQUp6VTCOUDKxVkJ2MORQSXpxYTFLS28vN3N3ZnRVK2RtVm84UIE9;NDQyMTM3QDMxMzkyZTMxMmUzMGEST20vOE84SFJaektDbmYrVmxLN3M5S2FWU1IrRINFbjh6ZH03TKNEV2c9");

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddHttpClient<IEmployeeService, EmployeeService>(client =>
{
    client.BaseAddress =new Uri(builder.HostEnvironment.BaseAddress);
});

//builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
builder.Services.AddSyncfusionBlazor();

await builder.Build().RunAsync();
