using EmployeeManagement_Blazor.Client;
using EmployeeManagement_Blazor.Client.Services;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Syncfusion.Blazor;



Syncfusion.Licensing.SyncfusionLicenseProvider.RegisterLicense("NTM2MzcxQDMxMzkyZTMzMmUzMEFQUWZ1UGlGV1JvNUhua2JHdzdTVlVIcVIvUVd0UlE0bmVzK1BGNVhrY1U9; NTM2MzcyQDMxMzkyZTMzMmUzMFQvM2lJSzVnZ2Z2eGI3bmtrSVlueFUyS1NHRFRUVTkrMmxxUmdLeEZEeWc9; NTM2MzczQDMxMzkyZTMzMmUzMEhWWUhYZ09MQUxXYTgySDNpQ3BNMlNCT1lwcEpjanlmai9PR25XMXVOM0k9; NTM2Mzc0QDMxMzkyZTMzMmUzMGd5OVJnaENtREVOWWRwN3Myc0RobjZCVmtjTXcyTGpvNmUzdjVpbXJ2L009; NTM2Mzc1QDMxMzkyZTMzMmUzMFkzWlBicWozR2NjRFNWbFBBTk80YjFyU0VabmdvZWZlNzMzekFHVXczb289; NTM2Mzc2QDMxMzkyZTMzMmUzMGRtVWxmeUtTWTFSM2xEcm42ekpCZmdHVXBYRlRlRllxdkVITTh6YXF4NVE9; NTM2Mzc3QDMxMzkyZTMzMmUzMFJkMDRZck1vSzBoSmdoVkw4TE1HQjFtZFRPU3o4ejJraU5tbWNqNk4vUm89; NTM2Mzc4QDMxMzkyZTMzMmUzMGpKM0xKbVRUR1B2U3dkS2UxZzMzVE5RSEdDRzFDcG4zaEJWYzcxUGRqTjA9; NTM2Mzc5QDMxMzkyZTMzMmUzMGFvQnZPRmlNeWtITlQySktTZkZCUEdVbTBqWEl6OUNackVLcXFtYXkydTA9; NTM2MzgwQDMxMzkyZTMzMmUzMGw5RnB2bVVWano4Nzl0NGVENzg5UEtKYlkxWkZsWUp4Z2lVcEs5S3R2NDA9; NTM2MzgxQDMxMzkyZTMzMmUzME85RnZsOHp5UEFOMjRYL1UwOTRpK2xaQmI4b0NCZmhVZkNnTGFYUytRaXM9");

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddHttpClient<IEmployeeService, EmployeeService>(client =>
{
    client.BaseAddress =new Uri(builder.HostEnvironment.BaseAddress);
});

//builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
builder.Services.AddSyncfusionBlazor();
builder.Services.AddScoped<EmployeeAdaptor>();

await builder.Build().RunAsync();
